### ISSUE TITLE
anonym.to links to bitcoin scam

### ISSUE THREAD

**Issue by Manos654764** [lkrjangid1/Awesome-Warez#5]
almost all links on this site lead to this site: https://affgate.top/landing/aff/\
please fix this.

proof:
![AbHN10Krfs](https://github.com/lkrjangid1/Awesome-Warez/assets/113250996/dc7fe3d1-5b27-48df-bee3-6f638c60fac4)

**Comment by lkrjangid1** [comment]
Done
